version: '3.8'
services:
  angular-app:
    image: horizon-capsule2
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      -
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Map HTTP port 80 on the host to Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount Nginx configuration
    depends_on:
      - app  # Ensure app starts first

